# Generated by Django 5.0.3 on 2024-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=200)),
                ('recipeDescription', models.TextField()),
                ('recipeImage', models.ImageField(upload_to='recipeMedia')),
            ],
        ),
    ]
