# Generated by Django 5.0.3 on 2024-04-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_studentreportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentreportcard',
            unique_together={('student_rank', 'date_of_reportCard_generation')},
        ),
    ]
