# Generated by Django 5.0.3 on 2024-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_alter_studentreportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreportcard',
            name='date_of_reportCard_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
